version: '3.9'
services:

    jenkins:
        container_name: jenkins_rest
        image: jenkins/jenkins
        ports:
            - 8080:8080
        volumes:
            - ${PWD}/jenkins_home:/var/jenkins_home
        environment:
            - DOCKER_HOST=tcp://socat:2375
        links:
            - socat

    socat:
        container_name: socat_rest
        image: alpine/socat
        ports:
            - 2375:2375
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        command: tcp-listen:2375,fork,reuseaddr unix-connect:/var/run/docker.sock

